name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  byte-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Emacs
        run: sudo apt-get update && sudo apt-get install -y emacs-nox
      - name: Byte compile
        run: |
          emacs --batch -Q -f batch-byte-compile init.el alter/*.el
