name: CI

on:
  push:
    branches:
      - master
      - work
      - codex/*
      - feature/*
  pull_request:

jobs:
  byte-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Emacs
        run: sudo apt-get update && sudo apt-get install -y emacs-nox
      - name: Install packages
        run: |
          emacs -Q --batch -l init.el \
            --eval "(require 'package)" \
            --eval "(package-refresh-contents)" \
            --eval "(package-install-selected-packages)"
      - name: Byte compile
        run: |
          emacs -Q --batch -l init.el \
            -f batch-byte-compile init.el alter/*.el
